### ISSUE TITLE
No work in latin american client

### ISSUE THREAD

**Issue by Gilemcio** [keyboardturner/ItemUpgradeQualityIcons#1]
elseif LOCALE == "esMX" then

	categoryEnum = {
		Explorer = "Expedicionario",
		Adventurer = "Aventurero",
		Veteran = "Veterano",
		Champion = "Campeón",
		Hero = "Héroe",
	};

**Comment by keyboardturner** [comment]
Hi, thanks for bringing this to my attention. I will try to push a fix to this soon. I was under the impression esMX would default to esES.
